'''
   Each new term in the Fibonacci sequence is
   generated by adding the previous two terms.
   By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence
   whose values do not exceed four million, find the
   sum of the even-valued terms.
'''

def compute(num):
#makes the fibonacci sequence
    fib = [1, 2]
    n1 = 1
    n2 = 2
    for x in range(num-2):
        new = n1+n2
        fib.append(new)
        n1 = n2
        n2 = new

#finds the sum of all even numbers
    ans = sum([f for f in fib if f%2 ==0 and f<=4000000])


    return  ans


print(compute(99999))



